DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Dynamic\VirtualSelector\Extension\BaseElementDataExtension

DNADesign\ElementalVirtual\Model\ElementVirtual:
  extensions:
    - Dynamic\VirtualSelector\Extension\ElementVirtualDataExtension
